### ISSUE TITLE
Running the GUI?

### ISSUE THREAD

**Issue by lokitkhemka** [enokjun/2D-and-3D-LEM-Slope-Analysis-Python3#1]
Hi,

You linked the following project: https://github.com/henrysha/3D-LEM-GUI

However, I cannot seem to be able to run the GUI project? I installed the dependencies with `npm install`, but I was not able run the application. I cannot ask for help on that link because the project is now archived and I cannot interact with in any way.

Any help you can provide will be appreciated. Thank you.

EDIT: If you can provide input files and some documentation related to running the slope stability analysis files, I would be grateful. I need it, especially for the 3d analysis for reference purposes.

**Comment by lokitkhemka** [comment]
Project abandoned.

**Comment by tarsioonofrio** [comment]
@lokitkhemka, were you able to run the scripts?

I'm trying to use the csv files present in the repository linked to this project but none of them work so far

**Comment by lokitkhemka** [comment]
Hi,

I was unable to run the scripts. I found the alternative with Scoops3D:
https://www.usgs.gov/software/scoops3d

It is in Fortran, but it has samples and good documentation too. Maybe it will help you too.

**Comment by tarsioonofrio** [comment]
Hi, thanks for your answer, i will check this software.

I found a manner to run the scripts. You will need to restore the file [`test inputs for analysis.csv`](https://github.com/enokjun/2D-and-3D-LEM-Slope-Analysis-Python3/commit/8c63a8fa1ea7bb1ded2d61c6a06cbee873581f6c#diff-c17c2e905cf5a97df95c19a4c8040e2b6b4acf5ff3318bf923674c5e30842e60) that is used in `Analysis_2D_Combined_V2.py`. 

Other files maybe help:
- [`test inputs for Spencer method.xlsx`](https://github.com/enokjun/2D-and-3D-LEM-Slope-Analysis-Python3/commit/5193677db3ef283d7e68e190184cf159d7c5d194#diff-ed55514e937cd283175ee2d27d731f78ccb0e26c58d8fff88419320b5ab63303)
- [`2D_LEM_Analysis/test inputs for Spencer method.csv`](https://github.com/enokjun/2D-and-3D-LEM-Slope-Analysis-Python3/commit/ff4a5ff9f3a3014e948f22e72c7f0d3b3f3ac7b2#diff-9c1fa44eded11ce65c8f688ac7065d7d000826bac2aa1b30123c719470508172)

**Comment by lokitkhemka** [comment]
Hi, did you manage work out the input for 3d file?

Thank you.

**Comment by tarsioonofrio** [comment]
I didn't test it for 3d, and I don't remember seeing any files for 3d scripts in the old commits unfortunately.

**Comment by lokitkhemka** [comment]
Yeah, It was the same for me. I didn't see any input files for 3d. Well, nothing can be done, I guess.

**Comment by tarsioonofrio** [comment]
I looked at the 3D-LEM-GUI code and it looks like it's just for file preview or visualization.

I looked at the function that reads the csv in 3d and 2d and they are the same.

I think it's possible to do something:

- The input files for the overall_3D_backend function in the Analysis_3D_Combined_V2.py file are these:
gwLevel3D.csv
bedrockLayer3D.csv
weakLayer3D.csv
groundSurface3D.csv

If you look at the 3D-LEM-GUI repository the files have these names:

interpolated_bedrockLayer2D.csv
interpolated_bedrockLayer3D.csv
interpolated_groundSurface2D.csv
interpolated_groundSurface3D.csv
interpolated_gwLevel2D.csv
interpolated_gwLevel3D.csv
interpolated_ss_type2.csv
interpolated_weakLayer2D.csv
interpolated_weakLayer3D.csv

If you remove 'interpolated_' from the 3D-LEM-GUI repository files, some of them will match the files needed for the overall_3D_backend of the Analysis_3D_Combined_V2.py file


- The input file of one of the select3DMethod function calls is 3DanalysisInputFile_ss2.csv and The interpolated_ss_type2.csv file from the 3D-LEM-GUI repository also has the 'suffix' 'ss'. Maybe you can use interpolated_ss_type2.csv in the select3DMethod function and 3DanalysisInputFile_ss2.csv, you will probably need to be careful to test several parameters.



I haven't tested any of this, I just took a look at the code, hope it helps.
